2025-03-02 14:55:43,258 - civileads - INFO - Trying URL: https://www.desmoines.gov
2025-03-02 14:55:43,329 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C5F90>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:44,331 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB8690>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:45,335 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB8B90>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:46,337 - civileads - INFO - Max retries exceeded for https://www.desmoines.gov
2025-03-02 14:55:46,337 - civileads - INFO - Trying URL: https://desmoines.gov
2025-03-02 14:55:46,387 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9310>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:47,389 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9810>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:48,392 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9BD0>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:49,394 - civileads - INFO - Max retries exceeded for https://desmoines.gov
2025-03-02 14:55:49,394 - civileads - INFO - Trying URL: https://www.desmoines.org
2025-03-02 14:55:52,629 - civileads - INFO - URL https://www.desmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:55:52,630 - civileads - INFO - Trying URL: https://desmoines.org
2025-03-02 14:55:52,863 - civileads - INFO - URL https://desmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:55:52,864 - civileads - INFO - Trying URL: https://www.desmoines.com
2025-03-02 14:55:53,037 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:55:54,088 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:55:55,142 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:55:56,181 - civileads - INFO - Max retries exceeded for https://www.desmoines.com
2025-03-02 14:55:56,181 - civileads - INFO - Trying URL: https://www.cityofdesmoines.gov
2025-03-02 14:55:56,240 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7750>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:57,243 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6850>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:58,245 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA710>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:55:59,247 - civileads - INFO - Max retries exceeded for https://www.cityofdesmoines.gov
2025-03-02 14:55:59,248 - civileads - INFO - Trying URL: https://www.cityofdesmoines.org
2025-03-02 14:55:59,457 - civileads - INFO - URL https://www.cityofdesmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:55:59,457 - civileads - INFO - Trying URL: https://www.cityofdesmoines.com
2025-03-02 14:55:59,517 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9BD0>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:00,520 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9950>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:01,523 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9450>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:02,526 - civileads - INFO - Max retries exceeded for https://www.cityofdesmoines.com
2025-03-02 14:56:02,527 - civileads - INFO - Trying URL: https://des-moines.gov
2025-03-02 14:56:02,579 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA0D0>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:03,581 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB8A50>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:04,583 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB8910>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:05,586 - civileads - INFO - Max retries exceeded for https://des-moines.gov
2025-03-02 14:56:05,587 - civileads - INFO - Trying URL: https://www.des-moines.gov
2025-03-02 14:56:05,646 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6850>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:06,648 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7750>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:07,650 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7ED0>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:08,652 - civileads - INFO - Max retries exceeded for https://www.des-moines.gov
2025-03-02 14:56:08,653 - civileads - INFO - Trying URL: https://des-moines.org
2025-03-02 14:56:08,711 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6710>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:09,714 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB8F50>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:10,720 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9090>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:11,723 - civileads - INFO - Max retries exceeded for https://des-moines.org
2025-03-02 14:56:11,723 - civileads - INFO - Trying URL: https://www.des-moines.org
2025-03-02 14:56:11,779 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9BD0>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:12,886 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA210>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:13,948 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA350>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:15,003 - civileads - INFO - Max retries exceeded for https://www.des-moines.org
2025-03-02 14:56:15,004 - civileads - INFO - Trying URL: https://desmoines.ia.us
2025-03-02 14:56:15,061 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAFD0>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:16,110 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABB4D0>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:17,144 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABB890>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:18,193 - civileads - INFO - Max retries exceeded for https://desmoines.ia.us
2025-03-02 14:56:18,194 - civileads - INFO - Trying URL: https://www.desmoines.ia.us
2025-03-02 14:56:18,245 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C5F90>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:19,296 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C65D0>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:20,330 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C74D0>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:21,406 - civileads - INFO - Max retries exceeded for https://www.desmoines.ia.us
2025-03-02 14:56:21,407 - civileads - INFO - Trying URL: https://des-moines.ia.us
2025-03-02 14:56:21,495 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAE90>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:22,498 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA5D0>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:23,500 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA490>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:24,502 - civileads - INFO - Max retries exceeded for https://des-moines.ia.us
2025-03-02 14:56:24,502 - civileads - INFO - Trying URL: https://www.des-moines.ia.us
2025-03-02 14:56:29,567 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923AB9810>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:56:35,631 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923AB96D0>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:56:41,698 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923AB9090>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:56:47,764 - civileads - INFO - Max retries exceeded for https://www.des-moines.ia.us
2025-03-02 14:56:47,765 - civileads - INFO - Trying URL: https://desmoines.ia.gov
2025-03-02 14:56:47,890 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9450>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:48,892 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB82D0>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:49,895 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABBED0>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:50,899 - civileads - INFO - Max retries exceeded for https://desmoines.ia.gov
2025-03-02 14:56:50,899 - civileads - INFO - Trying URL: https://www.desmoines.ia.gov
2025-03-02 14:56:50,941 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9090>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:51,943 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9810>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:52,945 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9E50>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:53,947 - civileads - INFO - Max retries exceeded for https://www.desmoines.ia.gov
2025-03-02 14:56:53,948 - civileads - WARNING - No working municipal website found for Des Moines, IA
2025-03-02 14:56:53,948 - civileads - INFO - Trying URL: https://www.desmoines.gov
2025-03-02 14:56:54,006 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAAD0>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:55,008 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAD50>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:56,011 - civileads - INFO - Retrying https://www.desmoines.gov after error: HTTPSConnectionPool(host='www.desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6850>: Failed to resolve 'www.desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:57,018 - civileads - INFO - Max retries exceeded for https://www.desmoines.gov
2025-03-02 14:56:57,018 - civileads - INFO - Trying URL: https://desmoines.gov
2025-03-02 14:56:57,069 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C5F90>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:58,071 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6710>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:56:59,074 - civileads - INFO - Retrying https://desmoines.gov after error: HTTPSConnectionPool(host='desmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E60410>: Failed to resolve 'desmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:00,077 - civileads - INFO - Max retries exceeded for https://desmoines.gov
2025-03-02 14:57:00,077 - civileads - INFO - Trying URL: https://www.desmoines.org
2025-03-02 14:57:00,298 - civileads - INFO - URL https://www.desmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:57:00,298 - civileads - INFO - Trying URL: https://desmoines.org
2025-03-02 14:57:00,496 - civileads - INFO - URL https://desmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:57:00,496 - civileads - INFO - Trying URL: https://www.desmoines.com
2025-03-02 14:57:00,682 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:57:01,736 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:57:02,792 - civileads - INFO - Retrying https://www.desmoines.com after error: HTTPSConnectionPool(host='www.desmoines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.desmoines.com'. (_ssl.c:1028)")))
2025-03-02 14:57:03,838 - civileads - INFO - Max retries exceeded for https://www.desmoines.com
2025-03-02 14:57:03,838 - civileads - INFO - Trying URL: https://www.cityofdesmoines.gov
2025-03-02 14:57:03,911 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7ED0>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:04,913 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7390>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:05,916 - civileads - INFO - Retrying https://www.cityofdesmoines.gov after error: HTTPSConnectionPool(host='www.cityofdesmoines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7890>: Failed to resolve 'www.cityofdesmoines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:06,920 - civileads - INFO - Max retries exceeded for https://www.cityofdesmoines.gov
2025-03-02 14:57:06,920 - civileads - INFO - Trying URL: https://www.cityofdesmoines.org
2025-03-02 14:57:07,163 - civileads - INFO - URL https://www.cityofdesmoines.org works but doesn't appear to be a municipal site
2025-03-02 14:57:07,164 - civileads - INFO - Trying URL: https://www.cityofdesmoines.com
2025-03-02 14:57:07,217 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAE90>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:08,220 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9E50>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:09,223 - civileads - INFO - Retrying https://www.cityofdesmoines.com after error: HTTPSConnectionPool(host='www.cityofdesmoines.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9810>: Failed to resolve 'www.cityofdesmoines.com' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:10,226 - civileads - INFO - Max retries exceeded for https://www.cityofdesmoines.com
2025-03-02 14:57:10,227 - civileads - INFO - Trying URL: https://des-moines.gov
2025-03-02 14:57:10,278 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAC10>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:11,281 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB91D0>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:12,287 - civileads - INFO - Retrying https://des-moines.gov after error: HTTPSConnectionPool(host='des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E607D0>: Failed to resolve 'des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:13,290 - civileads - INFO - Max retries exceeded for https://des-moines.gov
2025-03-02 14:57:13,290 - civileads - INFO - Trying URL: https://www.des-moines.gov
2025-03-02 14:57:13,349 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E611D0>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:14,352 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E616D0>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:15,355 - civileads - INFO - Retrying https://www.des-moines.gov after error: HTTPSConnectionPool(host='www.des-moines.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB91D0>: Failed to resolve 'www.des-moines.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:16,358 - civileads - INFO - Max retries exceeded for https://www.des-moines.gov
2025-03-02 14:57:16,359 - civileads - INFO - Trying URL: https://des-moines.org
2025-03-02 14:57:16,477 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB96D0>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:17,479 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9BD0>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:18,482 - civileads - INFO - Retrying https://des-moines.org after error: HTTPSConnectionPool(host='des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA490>: Failed to resolve 'des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:19,484 - civileads - INFO - Max retries exceeded for https://des-moines.org
2025-03-02 14:57:19,484 - civileads - INFO - Trying URL: https://www.des-moines.org
2025-03-02 14:57:19,564 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA350>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:20,567 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7890>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:21,569 - civileads - INFO - Retrying https://www.des-moines.org after error: HTTPSConnectionPool(host='www.des-moines.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7390>: Failed to resolve 'www.des-moines.org' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:22,572 - civileads - INFO - Max retries exceeded for https://www.des-moines.org
2025-03-02 14:57:22,573 - civileads - INFO - Trying URL: https://desmoines.ia.us
2025-03-02 14:57:22,627 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7110>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:23,675 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6710>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:24,709 - civileads - INFO - Retrying https://desmoines.ia.us after error: HTTPSConnectionPool(host='desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E60550>: Failed to resolve 'desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:25,743 - civileads - INFO - Max retries exceeded for https://desmoines.ia.us
2025-03-02 14:57:25,743 - civileads - INFO - Trying URL: https://www.desmoines.ia.us
2025-03-02 14:57:25,790 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E61BD0>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:26,794 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E620D0>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:27,800 - civileads - INFO - Retrying https://www.desmoines.ia.us after error: HTTPSConnectionPool(host='www.desmoines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6710>: Failed to resolve 'www.desmoines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:28,803 - civileads - INFO - Max retries exceeded for https://www.desmoines.ia.us
2025-03-02 14:57:28,804 - civileads - INFO - Trying URL: https://des-moines.ia.us
2025-03-02 14:57:28,867 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7750>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:29,870 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C65D0>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:30,871 - civileads - INFO - Retrying https://des-moines.ia.us after error: HTTPSConnectionPool(host='des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C74D0>: Failed to resolve 'des-moines.ia.us' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:31,874 - civileads - INFO - Max retries exceeded for https://des-moines.ia.us
2025-03-02 14:57:31,874 - civileads - INFO - Trying URL: https://www.des-moines.ia.us
2025-03-02 14:57:36,947 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923ABA5D0>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:57:43,010 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923ABA710>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:57:49,048 - civileads - INFO - Retrying https://www.des-moines.ia.us after error: HTTPSConnectionPool(host='www.des-moines.ia.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027923ABA490>, 'Connection to www.des-moines.ia.us timed out. (connect timeout=5)'))
2025-03-02 14:57:55,125 - civileads - INFO - Max retries exceeded for https://www.des-moines.ia.us
2025-03-02 14:57:55,126 - civileads - INFO - Trying URL: https://desmoines.ia.gov
2025-03-02 14:57:55,168 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9D10>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:56,171 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9810>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:57,174 - civileads - INFO - Retrying https://desmoines.ia.gov after error: HTTPSConnectionPool(host='desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9090>: Failed to resolve 'desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:58,177 - civileads - INFO - Max retries exceeded for https://desmoines.ia.gov
2025-03-02 14:57:58,178 - civileads - INFO - Trying URL: https://www.desmoines.ia.gov
2025-03-02 14:57:58,260 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923E60910>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:57:59,321 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAC10>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:00,390 - civileads - INFO - Retrying https://www.desmoines.ia.gov after error: HTTPSConnectionPool(host='www.desmoines.ia.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9950>: Failed to resolve 'www.desmoines.ia.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:01,436 - civileads - INFO - Max retries exceeded for https://www.desmoines.ia.gov
2025-03-02 14:58:01,437 - civileads - WARNING - No working municipal website found for Des Moines, IA
2025-03-02 14:58:04,407 - civileads - INFO - Trying URL: https://www.cedarrapids.gov
2025-03-02 14:58:04,477 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9E50>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:05,480 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABA5D0>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:06,482 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923ABAD50>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:07,485 - civileads - INFO - Max retries exceeded for https://www.cedarrapids.gov
2025-03-02 14:58:07,485 - civileads - INFO - Trying URL: https://cedarrapids.gov
2025-03-02 14:58:07,538 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6850>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:08,541 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C5F90>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:09,543 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6710>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:10,546 - civileads - INFO - Max retries exceeded for https://cedarrapids.gov
2025-03-02 14:58:10,547 - civileads - INFO - Trying URL: https://www.cedarrapids.org
2025-03-02 14:58:10,764 - civileads - INFO - Found working municipal URL: https://www.cedarrapids.org
2025-03-02 14:58:15,388 - civileads - INFO - Trying URL: https://www.cedarrapids.gov
2025-03-02 14:58:15,452 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6AD0>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:16,455 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C6C10>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:17,458 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7ED0>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:18,460 - civileads - INFO - Max retries exceeded for https://www.cedarrapids.gov
2025-03-02 14:58:18,461 - civileads - INFO - Trying URL: https://cedarrapids.gov
2025-03-02 14:58:18,506 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000279239C7D90>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:19,509 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB9A90>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:20,512 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027923AB82D0>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 14:58:21,514 - civileads - INFO - Max retries exceeded for https://cedarrapids.gov
2025-03-02 14:58:21,515 - civileads - INFO - Trying URL: https://www.cedarrapids.org
2025-03-02 14:58:21,700 - civileads - INFO - Found working municipal URL: https://www.cedarrapids.org
2025-03-02 14:58:22,040 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/contact
2025-03-02 14:58:22,492 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/directory
2025-03-02 14:58:23,317 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/elected-officials
2025-03-02 14:58:25,521 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/leadership
2025-03-02 15:07:19,606 - civileads - INFO - Trying URL: https://www.dsm.gov
2025-03-02 15:07:19,676 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176035F90>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:20,680 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176128050>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:21,683 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176128910>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:22,685 - civileads - INFO - Max retries exceeded for https://www.dsm.gov
2025-03-02 15:07:22,685 - civileads - INFO - Trying URL: https://dsm.gov
2025-03-02 15:07:22,744 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129090>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:23,746 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129450>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:24,749 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129810>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:25,752 - civileads - INFO - Max retries exceeded for https://dsm.gov
2025-03-02 15:07:25,752 - civileads - INFO - Trying URL: https://www.dmgov.org
2025-03-02 15:07:26,325 - civileads - INFO - Found working municipal URL: https://www.dmgov.org
2025-03-02 15:07:32,139 - civileads - INFO - Trying URL: https://www.dsm.gov
2025-03-02 15:07:32,201 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176036490>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:33,203 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176036850>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:34,209 - civileads - INFO - Retrying https://www.dsm.gov after error: HTTPSConnectionPool(host='www.dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176037250>: Failed to resolve 'www.dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:35,212 - civileads - INFO - Max retries exceeded for https://www.dsm.gov
2025-03-02 15:07:35,213 - civileads - INFO - Trying URL: https://dsm.gov
2025-03-02 15:07:35,256 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129F90>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:36,259 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129310>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:37,261 - civileads - INFO - Retrying https://dsm.gov after error: HTTPSConnectionPool(host='dsm.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176128F50>: Failed to resolve 'dsm.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:07:38,264 - civileads - INFO - Max retries exceeded for https://dsm.gov
2025-03-02 15:07:38,264 - civileads - INFO - Trying URL: https://www.dmgov.org
2025-03-02 15:07:38,812 - civileads - INFO - Found working municipal URL: https://www.dmgov.org
2025-03-02 15:07:39,175 - civileads - INFO - Found potential contact page: https://www.dmgov.org/contact
2025-03-02 15:07:39,546 - civileads - INFO - Found potential contact page: https://www.dmgov.org/directory
2025-03-02 15:07:39,912 - civileads - INFO - Found potential contact page: https://www.dmgov.org/staff
2025-03-02 15:07:40,274 - civileads - INFO - Found potential contact page: https://www.dmgov.org/officials
2025-03-02 15:07:40,648 - civileads - INFO - Found potential contact page: https://www.dmgov.org/elected-officials
2025-03-02 15:07:40,997 - civileads - INFO - Found potential contact page: https://www.dmgov.org/government
2025-03-02 15:07:41,347 - civileads - INFO - Found potential contact page: https://www.dmgov.org/departments
2025-03-02 15:07:41,698 - civileads - INFO - Found potential contact page: https://www.dmgov.org/administration
2025-03-02 15:07:42,042 - civileads - INFO - Found potential contact page: https://www.dmgov.org/city-hall
2025-03-02 15:07:42,396 - civileads - INFO - Found potential contact page: https://www.dmgov.org/about
2025-03-02 15:07:42,756 - civileads - INFO - Found potential contact page: https://www.dmgov.org/leadership
2025-03-02 15:07:43,166 - civileads - INFO - Found potential contact page: https://www.dmgov.org/city-council
2025-03-02 15:07:43,660 - civileads - INFO - Found potential contact page: https://www.dmgov.org/mayor
2025-03-02 15:07:44,046 - civileads - INFO - Found potential contact page: https://www.dmgov.org/clerk
2025-03-02 15:07:44,411 - civileads - INFO - Found potential contact page: https://www.dmgov.org/team
2025-03-02 15:07:44,770 - civileads - INFO - Found potential contact page: https://www.dmgov.org/council
2025-03-02 15:07:45,153 - civileads - INFO - Found potential contact page: https://www.dmgov.org/city-manager
2025-03-02 15:07:45,518 - civileads - INFO - Found potential contact page: https://www.dmgov.org/contact-us
2025-03-02 15:07:45,889 - civileads - INFO - Found potential contact page: https://www.dmgov.org/phone-directory
2025-03-02 15:07:46,274 - civileads - INFO - Found potential contact page: https://www.dmgov.org/employee-directory
2025-03-02 15:07:46,645 - civileads - INFO - Found potential contact page: https://www.dmgov.org/city-departments
2025-03-02 15:09:57,357 - civileads - INFO - Trying URL: https://www.ced.gov
2025-03-02 15:09:57,422 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176036210>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:09:58,426 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612AE90>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:09:59,428 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000181761291D0>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:00,431 - civileads - INFO - Max retries exceeded for https://www.ced.gov
2025-03-02 15:10:00,431 - civileads - INFO - Trying URL: https://ced.gov
2025-03-02 15:10:00,485 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000181761282D0>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:01,487 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612A350>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:02,490 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129450>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:03,492 - civileads - INFO - Max retries exceeded for https://ced.gov
2025-03-02 15:10:03,493 - civileads - INFO - Trying URL: https://www.cedarrapids.gov
2025-03-02 15:10:03,587 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741B110>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:04,590 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741B890>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:05,592 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741AFD0>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:06,595 - civileads - INFO - Max retries exceeded for https://www.cedarrapids.gov
2025-03-02 15:10:06,595 - civileads - INFO - Trying URL: https://cedarrapids.gov
2025-03-02 15:10:06,641 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741A0D0>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:07,647 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741A850>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:08,650 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817741AAD0>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:09,653 - civileads - INFO - Max retries exceeded for https://cedarrapids.gov
2025-03-02 15:10:09,653 - civileads - INFO - Trying URL: https://www.cedarrapids.org
2025-03-02 15:10:09,934 - civileads - INFO - Found working municipal URL: https://www.cedarrapids.org
2025-03-02 15:10:15,417 - civileads - INFO - Trying URL: https://www.ced.gov
2025-03-02 15:10:15,480 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129F90>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:16,482 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612B390>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:17,484 - civileads - INFO - Retrying https://www.ced.gov after error: HTTPSConnectionPool(host='www.ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612A710>: Failed to resolve 'www.ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:18,486 - civileads - INFO - Max retries exceeded for https://www.ced.gov
2025-03-02 15:10:18,486 - civileads - INFO - Trying URL: https://ced.gov
2025-03-02 15:10:18,529 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612AFD0>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:19,531 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612B250>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:20,533 - civileads - INFO - Retrying https://ced.gov after error: HTTPSConnectionPool(host='ced.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176128690>: Failed to resolve 'ced.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:21,535 - civileads - INFO - Max retries exceeded for https://ced.gov
2025-03-02 15:10:21,536 - civileads - INFO - Trying URL: https://www.cedarrapids.gov
2025-03-02 15:10:21,592 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612A350>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:22,599 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000181761287D0>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:23,601 - civileads - INFO - Retrying https://www.cedarrapids.gov after error: HTTPSConnectionPool(host='www.cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176128690>: Failed to resolve 'www.cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:24,604 - civileads - INFO - Max retries exceeded for https://www.cedarrapids.gov
2025-03-02 15:10:24,604 - civileads - INFO - Trying URL: https://cedarrapids.gov
2025-03-02 15:10:24,654 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001817612AFD0>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:25,656 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129A90>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:26,659 - civileads - INFO - Retrying https://cedarrapids.gov after error: HTTPSConnectionPool(host='cedarrapids.gov', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018176129950>: Failed to resolve 'cedarrapids.gov' ([Errno 11001] getaddrinfo failed)"))
2025-03-02 15:10:27,661 - civileads - INFO - Max retries exceeded for https://cedarrapids.gov
2025-03-02 15:10:27,662 - civileads - INFO - Trying URL: https://www.cedarrapids.org
2025-03-02 15:10:27,783 - civileads - INFO - Found working municipal URL: https://www.cedarrapids.org
2025-03-02 15:10:28,086 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/contact
2025-03-02 15:10:28,546 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/directory
2025-03-02 15:10:29,251 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/elected-officials
2025-03-02 15:10:30,985 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/leadership
2025-03-02 15:10:32,935 - civileads - INFO - Found potential contact page: https://www.cedarrapids.org/contact-us
